[package]
name = "futures-diagnose-exec"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
edition = "2018"
description = "Wraps around a Spawn and provides lots of diagnostics"

[dependencies]
futures-preview = "0.3.0-alpha.17"
log = "0.4.8"
